import {
  AuthCredentialType,
  Prisma,
  PrismaClient,
  UserPresenceStatus,
} from '@prisma/client';
import * as argon2 from 'argon2';
import { mkdir, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import { randomUUID } from 'node:crypto';
import { OrgRole, WorkspaceRole } from '../../src/common/constants/permissions';
import { batchInsert, dateInRange, getFaker, weightedPick } from './helpers';

export type SeedUsersDeps = {
  prisma: PrismaClient;
};

export type SeedUsersResult = {
  organizationId: string;
  workspaceId: string;
  agentIds: string[];
  workspaceMemberIds: string[];
  workspaceMemberByUserId: Map<string, string>;
  loginCredentialsPath: string;
};

const AGENT_COUNT = 1000;
const DEMO_PASSWORD = 'AxoDeskDemo#2026';
const LOGIN_CREDENTIALS_FILE = 'login-users.seed';

type SeedLoginCredential = {
  userId: string;
  email: string;
  password: string;
  orgRole: OrgRole;
  workspaceRole: WorkspaceRole;
  workspaceId: string;
  organizationId: string;
};

function pickOrgRole(index: number): OrgRole {
  if (index === 0) {
    return OrgRole.ADMIN;
  }

  if (index === 1) {
    return OrgRole.BILLING_ADMIN;
  }

  if (index <= 3) {
    return OrgRole.USER_ADMIN;
  }

  return OrgRole.MEMBER;
}

function pickWorkspaceRole(index: number): WorkspaceRole {
  if (index === 0) {
    return WorkspaceRole.OWNER;
  }

  if (index <= 7) {
    return WorkspaceRole.MANAGER;
  }

  return WorkspaceRole.AGENT;
}

async function hashSeedPassword(password: string): Promise<string> {
  return argon2.hash(password, {
    type: argon2.argon2id,
    memoryCost: Number(process.env.AUTH_ARGON2_MEMORY_COST ?? 19456),
    timeCost: Number(process.env.AUTH_ARGON2_TIME_COST ?? 3),
    parallelism: Number(process.env.AUTH_ARGON2_PARALLELISM ?? 1),
  });
}

async function writeLoginCredentialsFile(
  credentials: SeedLoginCredential[],
): Promise<string> {
  const filePath = path.resolve(__dirname, LOGIN_CREDENTIALS_FILE);
  const payload = {
    generatedAt: new Date().toISOString(),
    note: 'Local demo login credentials generated by prisma/seed. This *.seed file is gitignored.',
    loginUrlHint: '/login',
    users: credentials,
  };

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8');

  return filePath;
}

export async function seedUsers({
  prisma,
}: SeedUsersDeps): Promise<SeedUsersResult> {
  const faker = getFaker();
  const now = new Date();
  const twoYearsAgo = new Date(now);
  twoYearsAgo.setFullYear(now.getFullYear() - 2);

  const organizationId = randomUUID();
  const workspaceId = randomUUID();
  const organizationCreatedAt = dateInRange(
    twoYearsAgo,
    new Date(now.getTime() - 1000 * 60 * 60 * 24 * 420),
  );
  const workspaceCreatedAt = dateInRange(
    organizationCreatedAt,
    new Date(now.getTime() - 1000 * 60 * 60 * 24 * 390),
  );

  const organizationRows: Prisma.OrganizationCreateManyInput[] = [
    {
      id: organizationId,
      name: `${faker.company.name()} Support`,
      website: `https://${faker.internet.domainName()}`,
      plan: 'growth',
      onboardingData: {
        source: 'seed',
        companySize: '51-200',
        primaryUseCase: 'omnichannel-support',
      },
      onboardingCompletedAt: dateInRange(workspaceCreatedAt, now),
      createdAt: organizationCreatedAt,
    },
  ];

  const workspaceRows: Prisma.WorkspaceCreateManyInput[] = [
    {
      id: workspaceId,
      organizationId,
      name: 'AxoDesk Demo Workspace',
      timeZone: 'Asia/Kolkata',
      language: 'en',
      dateFormat: 'DD/MM/YYYY',
      timeFormat: 'hh:mm A',
      notificationInactivityTimeoutSec: 300,
      onboardingDismissed: true,
      onboardingCompleted: true,
      createdAt: workspaceCreatedAt,
    },
  ];

  const userRows: Prisma.UserCreateManyInput[] = [];
  const organizationMemberRows: Prisma.OrganizationMemberCreateManyInput[] = [];
  const workspaceMemberRows: Prisma.WorkspaceMemberCreateManyInput[] = [];
  const userActivityRows: Prisma.UserActivityCreateManyInput[] = [];
  const authCredentialRows: Prisma.AuthCredentialCreateManyInput[] = [];
  const loginCredentials: SeedLoginCredential[] = [];
  const agentIds: string[] = [];
  const workspaceMemberIds: string[] = [];
  const workspaceMemberByUserId = new Map<string, string>();
  const passwordHash = await hashSeedPassword(DEMO_PASSWORD);

  for (let index = 0; index < AGENT_COUNT; index += 1) {
    const userId = randomUUID();
    const workspaceMemberId = randomUUID();
    const firstName = faker.person.firstName();
    const lastName = faker.person.lastName();
    const createdAt = dateInRange(workspaceCreatedAt, now);
    const joinedAt = dateInRange(createdAt, now);
    const orgRole = pickOrgRole(index);
    const workspaceRole = pickWorkspaceRole(index);
    const availability = weightedPick([
      { value: 'online', weight: 55 },
      { value: 'away', weight: 20 },
      { value: 'busy', weight: 15 },
      { value: 'offline', weight: 10 },
    ]);
    const lastSeenAt = dateInRange(joinedAt, now);

    agentIds.push(userId);
    workspaceMemberIds.push(workspaceMemberId);
    workspaceMemberByUserId.set(userId, workspaceMemberId);
    const email = `agent.${index + 1}.${faker.internet.username({ firstName, lastName }).toLowerCase()}@axodesk-demo.local`;

    userRows.push({
      id: userId,
      email,
      emailVerifiedAt: dateInRange(createdAt, now),
      firstName,
      lastName,
      avatarUrl: faker.image.avatar(),
      createdAt,
      language: 'en',
      status: 'ACTIVE',
      lastLoginAt: lastSeenAt,
    });

    organizationMemberRows.push({
      id: randomUUID(),
      organizationId,
      userId,
      role: orgRole,
      status: 'ACTIVE',
      joinedAt,
    });

    workspaceMemberRows.push({
      id: workspaceMemberId,
      workspaceId,
      userId,
      role: workspaceRole,
      status: 'ACTIVE',
      joinedAt,
      availability,
    });

    userActivityRows.push({
      userId,
      activityStatus: weightedPick([
        { value: UserPresenceStatus.ACTIVE, weight: 50 },
        { value: UserPresenceStatus.AWAY, weight: 20 },
        { value: UserPresenceStatus.BUSY, weight: 10 },
        { value: UserPresenceStatus.DND, weight: 5 },
        { value: UserPresenceStatus.OFFLINE, weight: 15 },
      ]),
      lastSeenAt,
      lastActivityAt:
        availability === 'offline' ? lastSeenAt : dateInRange(lastSeenAt, now),
      lastWorkspaceId: workspaceId,
      inactivitySessionId: randomUUID(),
    });

    authCredentialRows.push({
      id: randomUUID(),
      userId,
      type: AuthCredentialType.PASSWORD,
      passwordHash,
      passwordVersion: 1,
      passwordUpdatedAt: createdAt,
      passwordMigratedAt: null,
      mustRotatePassword: false,
      failedPasswordAttempts: 0,
      lockedUntil: null,
      passwordPolicyVersion: 1,
      createdAt,
      updatedAt: createdAt,
    });

    loginCredentials.push({
      userId,
      email,
      password: DEMO_PASSWORD,
      orgRole,
      workspaceRole,
      workspaceId,
      organizationId,
    });
  }

  await batchInsert<Prisma.OrganizationCreateManyInput>(
    prisma.organization,
    organizationRows,
  );
  await batchInsert<Prisma.WorkspaceCreateManyInput>(
    prisma.workspace,
    workspaceRows,
  );
  await batchInsert<Prisma.UserCreateManyInput>(prisma.user, userRows);
  await batchInsert<Prisma.OrganizationMemberCreateManyInput>(
    prisma.organizationMember,
    organizationMemberRows,
  );
  await batchInsert<Prisma.WorkspaceMemberCreateManyInput>(
    prisma.workspaceMember,
    workspaceMemberRows,
  );
  await batchInsert<Prisma.UserActivityCreateManyInput>(
    prisma.userActivity,
    userActivityRows,
  );
  await batchInsert<Prisma.AuthCredentialCreateManyInput>(
    prisma.authCredential,
    authCredentialRows,
  );

  const loginCredentialsPath =
    await writeLoginCredentialsFile(loginCredentials);

  return {
    organizationId,
    workspaceId,
    agentIds,
    workspaceMemberIds,
    workspaceMemberByUserId,
    loginCredentialsPath,
  };
}
